name: todo_list_redux
description: Creating a simple todo list using Redux
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: 3.10.5

dependencies:
  redux: 5.0.0
  flutter_redux: 0.10.0
  provider: 6.0.5
  shared_preferences: 2.2.0
  equatable: 2.0.5
  uuid: 3.0.7
  meta: 1.9.1
  get_it: 7.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  bloc_test: 9.1.3
  mocktail: 0.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
